# Generated by Django 4.1.3 on 2022-11-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_folders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='folders',
            name='access_by',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
