# Generated by Django 4.1.3 on 2022-11-20 10:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_folders_access_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folders',
            name='access_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=150), blank=True, default='', size=None),
        ),
    ]
